- name: "update yum packages."
  become: true
  yum:
    update_cache: true

- name: "upgrade packages"
  become: true
  yum:
    name: "*"
    state: latest

- name: "install node dependencies"
  become: true
  yum:
    name:
      - nodejs
      #- npm # TODO: additional steps required before installing this
    state: present
    update_cache: true

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present

- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy files"
  copy:
    src: artifact.tar.gz
    dest: ~/web
    backup: true
- name: extract the zipped artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/web
    
  
- name: "start server"
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start
   
