- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'


    
- name: extract the zipped artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/web
    
  
- name: "start server"
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start
   
