- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy Files
  ansible.builtin.copy:
    src: artifact.tar.gz
    dest: ~/web

- name: extract the zipped artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/web
    
    
- name: Executing node
  shell: | 
    cd ~/web/dist
    npm install
    pm2 stop default
    pm2 start main.js
    #pm2 start npm -- start
    
  register: excute_node
  
- name: print service status
  debug:
    msg: "{{excute_node.stdout_lines}}"

