- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy Files
  ansible.builtin.copy:
    src: artifact.tar.gz
    dest: ~/web

- name: extract the zipped artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/web
    
    
- name: Executing node
  shell: | 
    cd ~/web/dist
    npm install
    pm2 stop default
    pm2 start main.js
    #pm2 start npm -- start
    
  register: excute_node
  
- name: print service status
  debug:
    msg: "{{excute_node.stdout_lines}}

