version: 2.1
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
              cd frontend 
              npm install
              npm run build
            # Your code here
             #exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
              cd backend 
              npm install
              npm run build
             # Your code here
             #exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
          
  test-frontend:
    docker:
      # Docker image here
    steps:
      - checkout
      - restore_cache:
          paths: [frontend/node_modules]
          keys: [frontend-build]
      - run:
          name: test-frontend
          command: |
              cd frontend
              npm install
              npm run test
                
  test-backend:
    docker:
      # Docker image here
    steps:
      - checkout
      - restore_cache:
          paths: [backend/node_modules]
          keys: [backend-build]
      - run:
          name: test-backtend
          command: |
              cd backend
              npm install
              npm run test         
workflows:
  MyFinalProject:
    jobs:
      - say-hello
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: 
            - build-backend
 
